name: 'facebook_ads'
version: '0.6.0'
profile: 'FIVETRAN_TEST_FACEBOOK'
config-version: 2
require-dbt-version: [">=1.3.0", "<2.0.0"]
models:
  facebook_ads:
    +schema: fivetran_dbt_facebook_ads
    +materialized: table
    intermediate:
      +materialized: view
vars:
  facebook_ads_database: RYAN_MIRANDA_RAW
  facebook_ads_schema: DBT_MELTANO_FACEBOOK 
  fivetran_facebook:
    account_history: "{{ ref('stg_facebook_ads__account_history') }}"
    ad_history: "{{ ref('stg_facebook_ads__ad_history') }}"
    ad_set_history: "{{ ref('stg_facebook_ads__ad_set_history') }}"
#    TODO model 'basic_ad' model missing from Fivetran
    basic_ad: "{{ ref('stg_facebook_ads__basic_ad') }}"
    campaign_history: "{{ ref('stg_facebook_ads__campaign_history') }}"
    creative_history: "{{ ref('stg_facebook_ads__creative_history') }}"
    url_tag: "{{ ref('stg_facebook_ads__url_tag') }}"
